#!/usr/bin/env bash

VERSION='0.1.0'
BIN_PATH="$MDF_BIN_PATH"
VAR_PATH="$MDF_VAR_PATH"
LIB="$VAR_PATH/lib"
VENDOR="$VAR_PATH/vendor"
PROFILE_DIR="$VAR_PATH/profiles"
GIT_REMOTE="$VAR_PATH/.gitremote"
GIT_DIR="$VAR_PATH/.git"
GIT_WORK_TREE="$MDF_WORK_TREE"

# source vendored files
source "$VENDOR/pure-getopt/getopt.bash"

# source all lib files
for file in $(find "$LIB" -type f -name '*.bash') ; do
  source $file
done

usage() {
  cat <<EOB

  Usage: mdf <comand> [options]

  Command list:
  <usage | --help | -h>   : display this message
  <add>                   : add a new profile
  <list>                  : list available profiles
  <restore>               : restore working tree to original state
  <uninstall>             : uninstall mdf entirely
  <use>                   : deploy a selected dotfile set
  <version | --verison>   : print version number and exit

  You can also type \`mdf help <command>\` to learn more about a particular command.

  Happy coding!
EOB
}

COMMAND=$1
shift

if [ $COMMAND != 'uninstall' ] ; then
  quietly 'git_sentinel_commit'
fi

case $COMMAND in
  add)
    add "$@"
    ;;
  --help|-h|usage)
    usage
    ;;
  help)
    help "$@"
    ;;
  list)
    list
    ;;
  restore)
    restore
    ;;
  uninstall)
    uninstall "$@"
    ;;
  use)
    use "$@"
    ;;
  version|--version)
    echo $VERSION
    ;;
  *)
    echoerr 'Invalid command'
    exit 1
    ;;
esac

exit 0
