#!/usr/bin/env ruby
# vim:fileencoding=utf-8

$:.unshift ENV['PWD']

require 'spec/spec_helper'
require 'tmpdir'
require 'fileutils'
Dir['spec/*.rb'].each{ |f| require f }

def main(argv = [].freeze)
  MiniTest::Unit.output = Class.new do
    def puts(*args)
      args.each { |arg| announce! arg }
      $stderr.print "\n"
    end

    def print(*args)
      args.each { |arg| $stderr.print "#{GREEN}#{arg}#{RESET}" }
    end

    def announce!(something)
      $stderr.print "#{GOLD}golden#{RESET}: #{GREEN}#{something}#{RESET}"
    end
  end.new

  MiniTest::Spec.before do
    @tmp_var = Dir.mktmpdir(['mdf_', '_var'])
    @tmp_bin = Dir.mktmpdir(['mdf_', '_bin'])
    ENV['MDF_VAR_PATH'] = @tmp_var
    ENV['MDF_BIN_PATH'] = @tmp_bin
    ENV['PATH'] = "#{@tmp_bin}:#{ENV['PATH']}"
    shell_out "#{File.expand_path(File.dirname(__FILE__))}/script/install"
  end

  MiniTest::Spec.after do
    shell_out "#{@tmp_bin}/mdf uninstall"
    FileUtils.rm_rf([@tmp_var, @tmp_bin])
  end

  exit_code = MiniTest::Unit.new.run(argv)
  if exit_code == 0
    $stderr.puts BRIGHT_GREEN
    $stderr.puts <<-EOF.gsub(/^ {4}/, '')
      ✓✓      ✓✓ ✓✓✓✓ ✓✓    ✓✓
      ✓✓  ✓✓  ✓✓  ✓✓  ✓✓✓   ✓✓
      ✓✓  ✓✓  ✓✓  ✓✓  ✓✓✓✓  ✓✓
      ✓✓  ✓✓  ✓✓  ✓✓  ✓✓ ✓✓ ✓✓
      ✓✓  ✓✓  ✓✓  ✓✓  ✓✓  ✓✓✓✓
      ✓✓  ✓✓  ✓✓  ✓✓  ✓✓   ✓✓✓
       ✓✓✓  ✓✓✓  ✓✓✓✓ ✓✓    ✓✓
    EOF
    $stderr.puts RESET
  else
    $stderr.puts BRIGHT_RED
    $stderr.puts <<-EOF.gsub(/^ {4}/, '')
      ✘✘✘✘✘✘✘✘    ✘✘✘    ✘✘✘✘ ✘✘
      ✘✘         ✘✘ ✘✘    ✘✘  ✘✘
      ✘✘        ✘✘   ✘✘   ✘✘  ✘✘
      ✘✘✘✘✘✘   ✘✘     ✘✘  ✘✘  ✘✘
      ✘✘       ✘✘✘✘✘✘✘✘✘  ✘✘  ✘✘
      ✘✘       ✘✘     ✘✘  ✘✘  ✘✘
      ✘✘       ✘✘     ✘✘ ✘✘✘✘ ✘✘✘✘✘✘✘✘
    EOF
    $stderr.puts RESET
  end

  exit exit_code
end

if $0 == __FILE__
  exit main(ARGV)
end
