#!/bin/bash

function echoerr() {
  echo -e "\033[0;31m$1\033[0m" 2>&1
}

function echosuccess() {
  echo -e "\033[32;1m$1\033[02"
}

function ensure_git() {
  which git > /dev/null

  if [ $? -ne 0 ] ; then
    echoerr 'Make sure git is installed and in your PATH before installing'
    exit 42
  fi
}

function ensure_mdf_bin_path() {
  local bin_path="${MDF_BIN_PATH:-/usr/local/bin}"

  if [ ! -d "$bin_path" ] ; then
    echoerr "Make sure $bin_path exists before proceeding"
    exit 1
  fi

  echo "$PATH" | tr ':' '\n' | grep "$bin_path" > /dev/null

  if [ $? -ne 0 ] ; then
    echoerr "Make sure $bin_path is in your PATH before proceeding"
    exit 2
  fi
}

function main() {
  local var_path="${MDF_VAR_PATH:-/usr/local/var/mdf}"
  local bin_path="${MDF_BIN_PATH:-/usr/local/bin}"
  local work_tree="${MDF_WORK_TREE:-$HOME}"
  local top="$(dirname $(dirname $0))"
  ensure_git
  ensure_mdf_bin_path
  cat <<EOB > "$bin_path/mdf"
#!/usr/bin/env bash

MDF_VAR_PATH=$var_path MDF_BIN_PATH=$bin_path MDF_WORK_TREE=$work_tree $var_path/mdf \$@
EOB
  chmod +x "$bin_path/mdf"
  mkdir -p "$var_path"
  for item in profiles lib mdf vendor ; do
    cp -r "$top/$item" "$var_path"
  done
}

main "$@"
