#!/bin/bash

function echoerr() {
  echo -e "\033[0;31m$1\033[0m" 2>&1
}

function echosuccess() {
  echo -e "\033[32;1m$1\033[02"
}

function ensure_git() {
  which git > /dev/null

  if [ $? -ne 0 ] ; then
    echoerr 'Make sure git is installed and in your PATH before installing'
    exit 42
  fi
}

function ensure_mdf_bin_path() {
  local bin_path="${MDF_BIN_PATH:-/usr/local/bin}"

  if [ ! -d "$bin_path" ] ; then
    echoerr "Make sure $bin_path exists before proceeding"
    exit 1
  fi

  echo "$PATH" | tr ':' '\n' | grep "$bin_path" > /dev/null

  if [ $? -ne 0 ] ; then
    echoerr "Make sure $bin_path is in your PATH before proceeding"
    exit 2
  fi
}

function main() {
  local var_path="${MDF_VAR_PATH:-/usr/local/var/mdf}"
  local bin_path="${MDF_BIN_PATH:-/usr/local/bin}"
  local top="$(dirname $(dirname $0))"
  ensure_git
  ensure_mdf_bin_path
  cp "$top/mdf" "$bin_path"
  mkdir -p "$var_path"
  cp -r "$top/profiles" "$var_path"
}

main "$*"
